# Use root/example as user/password credentials
version: "3.9"
services:
  mariadb:
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aquatracking
      LANG: C.UTF-8
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "25:1025"
