name: "Deploy DEV environment"

permissions:
  contents: read
  packages: write

concurrency:
  group: DEV
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:dev
